# -*- coding: utf-8 -*-
"""efficientad_wood_custom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZZP_snv3nzkQXnZXYPm1d7v4y8ju1PIU
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install tifffile==2021.7.30 tqdm==4.56.0 scikit-learn==1.2.2 numpy==1.18.5 Pillow==7.0.0 scipy==1.7.1 tabulate==0.8.7

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/
!git clone https://github.com/nelson1425/EfficientAD.git

!pip install torchvision==0.15.2 --index-url https://download.pytorch.org/whl/cu118

import torch
import torchvision

print("Torch version:", torch.__version__)
print("Torchvision version:", torchvision.__version__)
print("CUDA version:", torch.version.cuda)

!pip uninstall numpy -y
!pip install numpy==1.26.4

"""MODEL EĞİTİMİ"""

!python /content/drive/MyDrive/EfficientAD/efficientad.py \
  --mvtec_ad_path '/content/drive/MyDrive/wood_dataset' \
  --weights '/content/drive/MyDrive/EfficientAD/models/teacher_small.pth' \
  --output_dir '/content/drive/MyDrive/outputs/efficient' \
  --subdataset wood \
  --model_size small \
  --imagenet_train_path none \
  --train_steps 800

"""train steps = 800, auc = 69.19"""

!python /content/drive/MyDrive/EfficientAD/efficientad.py \
  --mvtec_ad_path '/content/drive/MyDrive/wood_dataset' \
  --weights '/content/drive/MyDrive/EfficientAD/models/teacher_small.pth' \
  --output_dir '/content/drive/MyDrive/outputs/efficient' \
  --subdataset wood \
  --model_size small \
  --imagenet_train_path none \
  --train_steps 2400

"""train steps = 3200, auc = 0.8879, F1 = 0.8310
"""

!python /content/drive/MyDrive/EfficientAD/efficientad.py \
  --mvtec_ad_path '/content/drive/MyDrive/wood_dataset' \
  --weights '/content/drive/MyDrive/EfficientAD/models/teacher_small.pth' \
  --output_dir '/content/drive/MyDrive/outputs/efficient' \
  --subdataset wood \
  --model_size small \
  --imagenet_train_path none \
  --train_steps 3200
